[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
name = "hd44780_simulator"
version = "0.1.0"

[dependencies]
piston_window = "0.57.0"
image = "0.10.3"

[dependencies.lcd_hd44780]
git = "https://github.com/gyscos/hd44780"
